import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Home/Header";
import Providers from "./Providers";
import Navbar from "@/Components/Navbar";
import NavItems from "@/Components/NavItems";
import Footer from "@/Components/Home/Footer"
import Welcome from "@/Components/Welcome";
import SearchBox from "@/Components/SearchBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <Header/> */}
          {/* <SearchBox/> */}
          {/* <div className=" mt-5 h-0.5 bg-gray-600 dark:bg-slate-50"></div> */}
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
